/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as PredictifRouteImport } from './routes/predictif'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as OrientationRouteImport } from './routes/orientation'
import { Route as ClassementsRouteImport } from './routes/classements'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EtablissementsIndexRouteImport } from './routes/etablissements/index'
import { Route as EnseignantsIndexRouteImport } from './routes/enseignants/index'
import { Route as ElevesIndexRouteImport } from './routes/eleves/index'
import { Route as EtablissementsIdRouteImport } from './routes/etablissements/$id'
import { Route as ElevesIdRouteImport } from './routes/eleves/$id'

const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictifRoute = PredictifRouteImport.update({
  id: '/predictif',
  path: '/predictif',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const OrientationRoute = OrientationRouteImport.update({
  id: '/orientation',
  path: '/orientation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassementsRoute = ClassementsRouteImport.update({
  id: '/classements',
  path: '/classements',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtablissementsIndexRoute = EtablissementsIndexRouteImport.update({
  id: '/etablissements/',
  path: '/etablissements/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnseignantsIndexRoute = EnseignantsIndexRouteImport.update({
  id: '/enseignants/',
  path: '/enseignants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesIndexRoute = ElevesIndexRouteImport.update({
  id: '/eleves/',
  path: '/eleves/',
  getParentRoute: () => rootRouteImport,
} as any)
const EtablissementsIdRoute = EtablissementsIdRouteImport.update({
  id: '/etablissements/$id',
  path: '/etablissements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesIdRoute = ElevesIdRouteImport.update({
  id: '/eleves/$id',
  path: '/eleves/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/classements': typeof ClassementsRoute
  '/orientation': typeof OrientationRoute
  '/parametres': typeof ParametresRoute
  '/predictif': typeof PredictifRoute
  '/rapports': typeof RapportsRoute
  '/regions': typeof RegionsRoute
  '/eleves/$id': typeof ElevesIdRoute
  '/etablissements/$id': typeof EtablissementsIdRoute
  '/eleves/': typeof ElevesIndexRoute
  '/enseignants/': typeof EnseignantsIndexRoute
  '/etablissements/': typeof EtablissementsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/classements': typeof ClassementsRoute
  '/orientation': typeof OrientationRoute
  '/parametres': typeof ParametresRoute
  '/predictif': typeof PredictifRoute
  '/rapports': typeof RapportsRoute
  '/regions': typeof RegionsRoute
  '/eleves/$id': typeof ElevesIdRoute
  '/etablissements/$id': typeof EtablissementsIdRoute
  '/eleves': typeof ElevesIndexRoute
  '/enseignants': typeof EnseignantsIndexRoute
  '/etablissements': typeof EtablissementsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/classements': typeof ClassementsRoute
  '/orientation': typeof OrientationRoute
  '/parametres': typeof ParametresRoute
  '/predictif': typeof PredictifRoute
  '/rapports': typeof RapportsRoute
  '/regions': typeof RegionsRoute
  '/eleves/$id': typeof ElevesIdRoute
  '/etablissements/$id': typeof EtablissementsIdRoute
  '/eleves/': typeof ElevesIndexRoute
  '/enseignants/': typeof EnseignantsIndexRoute
  '/etablissements/': typeof EtablissementsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/classements'
    | '/orientation'
    | '/parametres'
    | '/predictif'
    | '/rapports'
    | '/regions'
    | '/eleves/$id'
    | '/etablissements/$id'
    | '/eleves/'
    | '/enseignants/'
    | '/etablissements/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/classements'
    | '/orientation'
    | '/parametres'
    | '/predictif'
    | '/rapports'
    | '/regions'
    | '/eleves/$id'
    | '/etablissements/$id'
    | '/eleves'
    | '/enseignants'
    | '/etablissements'
  id:
    | '__root__'
    | '/'
    | '/classements'
    | '/orientation'
    | '/parametres'
    | '/predictif'
    | '/rapports'
    | '/regions'
    | '/eleves/$id'
    | '/etablissements/$id'
    | '/eleves/'
    | '/enseignants/'
    | '/etablissements/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClassementsRoute: typeof ClassementsRoute
  OrientationRoute: typeof OrientationRoute
  ParametresRoute: typeof ParametresRoute
  PredictifRoute: typeof PredictifRoute
  RapportsRoute: typeof RapportsRoute
  RegionsRoute: typeof RegionsRoute
  ElevesIdRoute: typeof ElevesIdRoute
  EtablissementsIdRoute: typeof EtablissementsIdRoute
  ElevesIndexRoute: typeof ElevesIndexRoute
  EnseignantsIndexRoute: typeof EnseignantsIndexRoute
  EtablissementsIndexRoute: typeof EtablissementsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictif': {
      id: '/predictif'
      path: '/predictif'
      fullPath: '/predictif'
      preLoaderRoute: typeof PredictifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orientation': {
      id: '/orientation'
      path: '/orientation'
      fullPath: '/orientation'
      preLoaderRoute: typeof OrientationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classements': {
      id: '/classements'
      path: '/classements'
      fullPath: '/classements'
      preLoaderRoute: typeof ClassementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etablissements/': {
      id: '/etablissements/'
      path: '/etablissements'
      fullPath: '/etablissements/'
      preLoaderRoute: typeof EtablissementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enseignants/': {
      id: '/enseignants/'
      path: '/enseignants'
      fullPath: '/enseignants/'
      preLoaderRoute: typeof EnseignantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves/': {
      id: '/eleves/'
      path: '/eleves'
      fullPath: '/eleves/'
      preLoaderRoute: typeof ElevesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/etablissements/$id': {
      id: '/etablissements/$id'
      path: '/etablissements/$id'
      fullPath: '/etablissements/$id'
      preLoaderRoute: typeof EtablissementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves/$id': {
      id: '/eleves/$id'
      path: '/eleves/$id'
      fullPath: '/eleves/$id'
      preLoaderRoute: typeof ElevesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClassementsRoute: ClassementsRoute,
  OrientationRoute: OrientationRoute,
  ParametresRoute: ParametresRoute,
  PredictifRoute: PredictifRoute,
  RapportsRoute: RapportsRoute,
  RegionsRoute: RegionsRoute,
  ElevesIdRoute: ElevesIdRoute,
  EtablissementsIdRoute: EtablissementsIdRoute,
  ElevesIndexRoute: ElevesIndexRoute,
  EnseignantsIndexRoute: EnseignantsIndexRoute,
  EtablissementsIndexRoute: EtablissementsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
